# Generated by Django 2.1.4 on 2019-01-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('id',)},
        ),
    ]
